# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define jobs to be invoked later in a workflow.
jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  sonarqube:
    working_directory: ~/build
    docker:
      - image: cimg/base:current  # A base image that has more flexibility for installations
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Install SonarQube Scanner"
          command: |
            curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner.zip
            export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-linux/bin
      - run:
          name: "Run SonarQube scanner"
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            echo "Sonar org value is: $SONAR_ORG"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

# Orchestrate jobs using workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube
